### ISSUE TITLE
error Package "poetic" refers to a non-existing file

### ISSUE THREAD

**Issue by diegorocha1986** [arianacosta/poetic#10]
I'm trying to run the command on a project i've just created using create-react-app and i'm getting the following error:

> error Package "poetic" refers to a non-existing file '"/Users/drocha/www/labs/poetic"'

![image](https://user-images.githubusercontent.com/1749975/64567575-ee364080-d32e-11e9-9191-45392301cdd0.png)

Obs: my project it's in the folder "/Users/drocha/www/labs/test-hooks"

**Comment by arianacosta** [comment]
Hi @qix1986 thanks for submitting this issue!

I'm happy to look into that. Can you please tell me your version of `node` and `yarn`? I just tested it with a fresh install of `create-react-app` and it worked fine using the following versions: 

- Node: 10.16.0
- Yarn: 1.17.3

<img width="825" alt="Screen Shot 2019-09-09 at 6 49 39 PM" src="https://user-images.githubusercontent.com/13475001/64571726-bdf0a100-d332-11e9-8eb9-b070aa3da0c5.png">

**Comment by yuanhaoyu** [comment]
I have same question 
![image](https://user-images.githubusercontent.com/15946472/64597781-066a9600-d3e9-11e9-9e0b-a44c6c078fa6.png)

**Comment by arianacosta** [comment]
@yuanhaoyu Thank you for providing more info. I will continue to investigate this.

**Comment by diegorocha1986** [comment]
![image](https://user-images.githubusercontent.com/1749975/64619252-29308680-d3b8-11e9-9583-06c507f8a5f6.png)

Here is the versions of my node and yarn.

**Comment by arianacosta** [comment]
@qix1986 @yuanhaoyu I found the issue. It was an incorrect dependency setting. It should work now. Thanks for reporting 👍
