### ISSUE TITLE
Implement CI/CD for Publishing to NPM

### ISSUE THREAD

**Issue by arianacosta** [arianacosta/poetic#11]
Use Github Actions to automatically change upgrade the version and publish to NPM.

**Comment by oleg-koval** [comment]
Would you like to have set up semantic release for this one?

**Comment by arianacosta** [comment]
Hi @oleg-koval, That would be great, yes!

**Comment by oleg-koval** [comment]
@arianacosta I can take this one!

**Comment by oleg-koval** [comment]
@arianacosta can you please enable Actions in repo config?

**Comment by arianacosta** [comment]
@oleg-koval I think they are enabled: `Enable local and third party Actions for this repository `. Do I need to do anything apart from that?

**Comment by oleg-koval** [comment]
@arianacosta I would need `NPM_TOKEN` variable set in https://github.com/arianacosta/poetic/settings/secrets

You can generate `NPM_TOKEN` with npm CLI:

```bash
npm login
npm token create
```

**Comment by oleg-koval** [comment]
Found also some problems with tags detection:

```
8e14f8e v1.1.0
00e827f Upgraded to eslint v6.6.0
5585bd6 Improved compatibility for CRA projects with TS (#24)
eca4563 makes requires a warning on js files (#23)
b8b3e9a Upgrade ESLint to 6.5.1 (#20)
d6c2410 v1.0.4
3a3ebae improved release automation script
d82e337 added release script
31deaf0 deduplicating no-unused-vars
56db808 upgraded dependencies (#17)
264934a improved error messages when installing (#15)
a99543b improved js and ts rule interoperability (#14)
396f7d3 (tag: v1.0.3) updated version
3ffccce Merge branch 'hotfix/10-error-Package-poetic-refers-to-a-non-existing-file'
e85d108 fixed poetic dependency pointing to local files
0793081 (tag: v1.0.2) fixed readme typos
8f0dfbe improved sucess message
9544579 (tag: v1.0.1) updated version and video size
```

`8e14f8e v1.1.0` & `d6c2410 v1.0.4` were not properly tagged/created

**Comment by arianacosta** [comment]
Hey @oleg-koval I added the token to the secrets.

About the tags, yeah, that's probably because of the manual process, I had some issues when publishing it did an automatic commit. Anyhow, I think I cleaned up the tags, it should be good now. Thanks!

**Comment by oleg-koval** [comment]
@arianacosta will take a look at this soon! :)

**Comment by oleg-koval** [comment]
I have synced fork now, but semantic-release still has some problems with latest releases:

```
[9:44:43 AM] [semantic-release] › ℹ  The next release version is 1.0.4
```

It seems to ignore 1.0.5, 1.1.0 versions, but tags are present:

```
> git tags
v1.0.1
v1.0.2
v1.0.3
v1.0.4
v1.0.5
v1.1.0
```

**Comment by oleg-koval** [comment]
```
d66b43a (HEAD -> oleg-koval/ci/add-semantic-release-workflow) ci(release): add semantic release workflow
8caa239 (origin/master, origin/HEAD, master) Adds support for both yarn and npm. (#22)
01f2c32 updated readme
8e14f8e v1.1.0
00e827f Upgraded to eslint v6.6.0
5585bd6 Improved compatibility for CRA projects with TS (#24)
eca4563 makes requires a warning on js files (#23)
b8b3e9a Upgrade ESLint to 6.5.1 (#20)
d6c2410 v1.0.4
3a3ebae improved release automation script
d82e337 added release script
31deaf0 deduplicating no-unused-vars
56db808 upgraded dependencies (#17)
264934a improved error messages when installing (#15)
a99543b improved js and ts rule interoperability (#14)
396f7d3 (tag: v1.0.3) updated version
3ffccce Merge branch 'hotfix/10-error-Package-poetic-refers-to-a-non-existing-file'
e85d108 fixed poetic dependency pointing to local files
0793081 (tag: v1.0.2) fixed readme typos
8f0dfbe improved sucess message
9544579 (tag: v1.0.1) updated version and video size
17e190a added badges to readme
```

@arianacosta as you can see some commits have been tagged: `(tag: v1.0.3)`

**Comment by oleg-koval** [comment]
@arianacosta, I think I have a solution for it tested it on my fork:

Remove local tags that were incorrectly added:
`git tag -d v1.0.4 v1.0.5 v1.1.0`

Tag a commit that is missing own tag in our case its `3a3ebae improved release automation script` and `00e827f Upgraded to eslint v6.6.0`, v1.0.5 is missing in commit log:
```
git tag -a v1.0.4 d6c2410
git tag -a v1.1.0 8e14f8e
```

It will ask you to enter a commit message.

When you will try to push you will be notified that remote tag exists, you need to remove it:

```
git push --delete origin v1.0.4 v1.0.5 v1.1.0
```

And finally:

```
git push -f
```

**Comment by oleg-koval** [comment]
@arianacosta btw if you don't have enough time now you can add me temporarily to maintainers so I'll do dirty work :)

**Comment by arianacosta** [comment]
@oleg-koval I followed the instructions, also I added you as Collaborator. 

There are only two things I would like to ask you:

- Please do not publish the current version to NPM, is has some issues from the last PR.
- Could you please set up the pipeline in a way that doesn't automatically publish to NPM on each merge to master? I would like to group several PR's test them out and then release. 

Thank you very much!

**Comment by oleg-koval** [comment]
@arianacosta thanks for the help!

Sure, a new version will not be published before accepted pull request, which will trigger release after the merge to master.

Also, if you want automation of this process, semantic-release and versioning require to follow practice with commit messages https://www.conventionalcommits.org/en/v1.0.0-beta.2/  to give a possibility to semantic-release to distinguish which type of release needs to be published: patch, minor or major based on a keyword in a commit message.

**Comment by arianacosta** [comment]
@oleg-koval Fantastic! I went through the docs, it's very useful. 

One thing that is not clear to me is how to put these commit messages when having multiple commits in a  Pull Request. For instance, there's a feature branch with 5 commits, and then a PR is opened from that. Should each of those commits include a separate message or just the PR description itself?

**Comment by oleg-koval** [comment]
@arianacosta it depends on what strategy of merging is used for the repo. What I can suggest from my experience, a strategy that helps to keep commits in clean state is following approach:

> # Merge options
> [**disabled**] Allow merge commits 
> Add all commits from the head branch to the base branch with a merge commit.
> [**enabled**]Allow squash merging 
> Combine all commits from the head branch into a single commit in the base branch.
> [**disabled**]Allow rebase merging 
> Add all commits from the head branch onto the base branch individually.

So if you have a branch with N commits: the only first one will be considered as a commit that would reflect all changes in master. All others will be squashed. The only first commit should have a semantic keyword, for other its not required.

**Comment by oleg-koval** [comment]
@arianacosta question: I see there is `yarn.lock` file now at master, do you want to release to yarn as well?

**Comment by arianacosta** [comment]
@oleg-koval About the merge option, I agree. The squash merge is my favorite one because it encourages commits while developing, but it keeps the master history clean.

I'm not sure I understand the question about `yarn`. Just so you know, `npx` would do the initial install, but Poetic, in turn, will install the dependencies with `yarn`. I don't think we need to do anything with this for publishing.
