### ISSUE TITLE
Non react option

### ISSUE THREAD

**Issue by tobeycodes** [arianacosta/poetic#29]
I just added this to the frontend of a project and it works great! I want to also add it to the backend, but the backend obviously doesn't load React. Would you ever considering adding a flag that doesn't add the React parts to the ESLint config?

**Comment by arianacosta** [comment]
Hi @schrapel, 

Thanks for sending that suggestion. That makes sense, we can explore that, sure.

Just curious, are you experiencing any issues with the current setup when working with Node in the back end? The dependencies are `devDependencies` and they should not affect back-end applications functionality or deployment size.

**Comment by tobeycodes** [comment]
@arianacosta sorry for not being clear. It actually works fine but I just get a notice when running `code:clean` that it could not detect React in the application.

**Comment by arianacosta** [comment]
@schrapel Thanks for reporting that! I'll take a look to see if we can automate that issue, if not, then we could provide an option as well.

**Comment by waspeer** [comment]
This would be great!

**Comment by fabricionaweb** [comment]
Are there someone working on that?

I usually use this package for React, and would like to use for Node as well (excluding the react dependencies related, like mentioned).

May I help on that request

**Comment by arianacosta** [comment]
Thanks @fabricionaweb, that would be great. Feel free to submit a PR for that. It would be great to have an option to select:

- React + Node (default)
- React Only
- Node Only

What do you think?
