### ISSUE TITLE
Fix Publish Action

### ISSUE THREAD

**Issue by arianacosta** [arianacosta/poetic#34]
Publish to NPM Action fails with 

```
command: 'git push --tags https://x-access-token:[secure]@github.com/arianacosta/poetic.git HEAD:master',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'remote: error: GH006: Protected branch update failed for refs/heads/master.        \n' +
    'remote: error: At least 1 approving review is required by reviewers with write access.        \n' +
    'To https://github.com/arianacosta/poetic.git\n' +
    ' ! [remote rejected] HEAD -> master (protected branch hook declined)\n' +
    "error: failed to push some refs to 'https://x-access-token:[secure]@github.com/arianacosta/poetic.git'",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  pluginName: '@semantic-release/git'
}
```

How can we have automatic semantic releases while enforcing code reviews?

**Comment by oleg-koval** [comment]
So the problem here is because of Github action has not rights (known issue) to push to protected branch (master).
Will create a workaround for this.

**Comment by oleg-koval** [comment]
@arianacosta need some help from you if you don't mind:

- generate a new Github token (settings -> secrets). [Link for docs](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners#creating-and-using-secrets-encrypted-variables)

Scopes for this token:

**(enabled: read:packages, repo, write:packages)**

- add a new secret to the project with the name: "GITHUB_TOKEN_WORKAROUND" with generated in previous step token.
