### ISSUE TITLE
Error with module 'yargs'

### ISSUE THREAD

**Issue by stephane-r** [arianacosta/poetic#40]
Hello :)

I would like try Poetic on fresh project, but i've an error with `yargs` module using `npx` : 

`Error: Cannot find module 'yargs'`

I use latest Node 12.x, same result with 10.x. This error is only for latest Poetic version, 1.1.0 work nice :)

**Comment by drtobbyas** [comment]
I have this same issue

**Comment by arianacosta** [comment]
Thanks for reporting this. I’ll take a look shortly.

**Comment by stephane-r** [comment]
You roks, thank !

**Comment by drtobbyas** [comment]
Great
