### ISSUE TITLE
Eslint complain on optional chaining 

### ISSUE THREAD

**Issue by galangel** [arianacosta/poetic#49]
please help
`
function sayHello(){console.log('hello');
`
`
sayHello?.() //Parsing error: Expression expected.
`

**Comment by arianacosta** [comment]
Can you please provide the details of the language version?

**Comment by galangel** [comment]
I am sorry my Typescript version under devDependencies was 3.6.3, that's the default from Expo for react native projects, after installing latest and adding `no-unused-expressions` to eslint, the error resolved

**Comment by arianacosta** [comment]
Thanks for reporting that. We'll keep an eye out on new next updates.
